# Generated by Django 5.0.6 on 2024-05-20 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0002_voiture_garage_assigné_voiture_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('numero_devis', models.IntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.garage')),
            ],
        ),
        migrations.CreateModel(
            name='DevisField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(max_length=20)),
                ('value', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('devis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.devis')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solutions', models.TextField()),
                ('problems', models.TextField()),
                ('duree_diagnostic', models.IntegerField()),
                ('method_diagnostic', models.TextField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.garage')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.voiture')),
            ],
        ),
        migrations.AddField(
            model_name='devis',
            name='diagnostic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diagnostic.diagnostic'),
        ),
    ]
