# Generated by Django 5.0.6 on 2024-05-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devis',
            name='garage',
        ),
    ]
