# Generated by Django 5.0.6 on 2024-05-30 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostic', '0004_remove_devis_numero_devis'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='commentaire',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
