# Generated by Django 5.0.4 on 2024-05-09 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='admin_dashboard.marquevoiture')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_annee_fabrication', models.PositiveIntegerField()),
                ('car_kilometrage', models.PositiveIntegerField()),
                ('car_type_carburant', models.CharField(max_length=50)),
                ('car_transmission', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50)),
                ('car_numero_serie', models.CharField(max_length=100)),
                ('car_symptomes', models.TextField()),
                ('car_historique_maintenance', models.TextField()),
                ('car_codes_erreur', models.TextField(blank=True, null=True)),
                ('car_modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.modele')),
            ],
        ),
    ]
