# Generated by Django 5.0.4 on 2024-05-17 15:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueVoiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marque', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeles', to='admin_dashboard.marquevoiture')),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_vitesse', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('annee_fabrication', models.PositiveIntegerField()),
                ('kilometrage', models.PositiveIntegerField()),
                ('type_carburant', models.CharField(choices=[('Gasoil', 'Gasoil'), ('Super', 'Super'), ('Essence', 'Essence')], max_length=50)),
                ('transmission', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50)),
                ('numero_serie', models.CharField(max_length=100)),
                ('symptomes', models.TextField()),
                ('couleur_voiture', models.CharField(max_length=50)),
                ('historique_maintenance', models.TextField()),
                ('codes_erreur', models.TextField(blank=True, null=True)),
                ('photo_voiture', models.ImageField(upload_to='voitures/')),
                ('numero_chassi', models.CharField(max_length=50)),
                ('modele', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_dashboard.modele')),
            ],
        ),
    ]
