# Generated by Django 5.0.6 on 2024-05-20 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='garage_assigné',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_dashboard.garage'),
        ),
        migrations.AddField(
            model_name='voiture',
            name='statut',
            field=models.CharField(choices=[('en attente de diagnostic', 'En attente de diagnostic'), ('diagnostiquée', 'Diagnostiquée')], default='en attente de diagnostic', max_length=30),
        ),
    ]
