# Generated by Django 5.0.4 on 2024-05-09 23:26

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_rename_car_annee_fabrication_voiture_annee_fabrication_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='couleur_voiture',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voiture',
            name='nombre_de_vitesse',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo_voiture',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='voitures/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voiture',
            name='type_carburant',
            field=models.CharField(choices=[('Gasoil', 'Gasoil'), ('Super', 'Super'), ('Essence', 'Essence')], max_length=50),
        ),
    ]
