# Generated by Django 5.0.4 on 2024-05-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_voiture_immatriculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='annee_fabrication',
            field=models.DateField(),
        ),
    ]
