# Generated by Django 5.0.6 on 2024-05-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_voiture_garage_assigné_voiture_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voiture',
            old_name='garage_assigné',
            new_name='garage_assigne',
        ),
    ]
