# Generated by Django 5.0.4 on 2024-05-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_voiture_annee_fabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='j',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=1)),
            ],
        ),
    ]
