# Generated by Django 5.0.4 on 2024-05-17 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_delete_j'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Garage',
        ),
    ]
