# Generated by Django 5.0.4 on 2024-05-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_delete_garage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=100)),
                ('site_web', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('horaire', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('photo_garage', models.ImageField(upload_to='photo_garage/')),
                ('logo_garage', models.ImageField(upload_to='logo_garare/')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now=True)),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
