# Generated by Django 5.0.4 on 2024-04-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='type_client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Particulier', 'Particulier'), ('Entreprise', 'Entreprise')], max_length=20)),
            ],
        ),
    ]
