# Generated by Django 5.0.4 on 2024-04-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_profile_user_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='termes_accept',
        ),
    ]
